import { type Url } from "next/dist/shared/lib/router/router";

export type JobApplication = {
  id: string;
  title: string | null;
  dateApplied: Date;
  dateAppliedReadable: string | null;
  daysSinceInitialSubmission: number | null;
  jobURL: Url;
  jobSource: string | null;
  salary: string | null;
  salaryType: string | null;
  levelOfInterest: string | null;
  resume: boolean | null;
  resumeUploadURL: string | null;
  coverLetter: boolean | null;
  coverLetterUploadURL: string | null;
  project: boolean | null;
  projectURL: string | null;
  projectLink: string | null;
  stageOfApplication: number | null;
  notes: string[] | null;
  company: string | null;
  showingDetails: boolean | null;
  isArchived: boolean | null;
  autoArchived: boolean | null;
  lastActivityDate: Date | null;
  owner: string;
  jobType: string | null;
  isRemote: boolean | null;
  isUSBased: boolean | null;
  isOutsideUS: boolean | null;
  country: string | null;
  city: string | null;
  state: string | null;
};
